In [1]:
import torch

In [2]:
h = torch.randint(0, 5, (5, 10))
h

tensor([[4, 3, 3, 2, 1, 1, 3, 2, 1, 3],
        [3, 0, 0, 0, 4, 0, 4, 0, 2, 1],
        [3, 3, 0, 3, 4, 2, 1, 1, 3, 4],
        [2, 0, 1, 0, 0, 3, 3, 0, 4, 1],
        [4, 2, 2, 4, 2, 0, 3, 4, 2, 0]])

In [3]:
# encoder_out: [batch_size x seq_size x hidden_size]
encoder_out = torch.randint(0, 5, (5, 3, 10))
encoder_out

tensor([[[4, 2, 4, 2, 3, 4, 0, 4, 0, 1],
         [1, 3, 4, 1, 0, 2, 3, 0, 0, 0],
         [3, 2, 1, 0, 2, 0, 0, 3, 4, 4]],

        [[4, 2, 2, 2, 1, 1, 1, 4, 3, 0],
         [0, 0, 3, 0, 3, 1, 0, 1, 3, 4],
         [0, 0, 4, 2, 1, 1, 4, 1, 4, 0]],

        [[0, 0, 1, 2, 2, 2, 4, 1, 4, 2],
         [0, 4, 4, 2, 3, 4, 0, 1, 3, 1],
         [1, 2, 4, 4, 0, 2, 3, 2, 1, 3]],

        [[1, 4, 4, 1, 3, 4, 3, 3, 4, 0],
         [3, 4, 2, 3, 2, 2, 0, 3, 1, 1],
         [4, 0, 3, 0, 2, 0, 0, 4, 1, 1]],

        [[4, 0, 2, 4, 0, 2, 0, 4, 1, 4],
         [0, 3, 0, 4, 2, 4, 0, 4, 1, 4],
         [2, 0, 0, 2, 3, 1, 0, 2, 4, 0]]])

In [4]:
dot_product = torch.sum(encoder_out * h.unsqueeze(1), axis=2, dtype=torch.float32)
dot_product

tensor([[56., 38., 45.],
        [26., 22., 28.],
        [43., 52., 45.],
        [43., 19., 16.],
        [54., 44., 38.]])

In [5]:
softmax = torch.nn.Softmax(1)
raspredelenie = softmax(dot_product)
raspredelenie

tensor([[9.9998e-01, 1.5230e-08, 1.6701e-05],
        [1.1894e-01, 2.1785e-03, 8.7888e-01],
        [1.2328e-04, 9.9897e-01, 9.1094e-04],
        [1.0000e+00, 3.7751e-11, 1.8795e-12],
        [9.9995e-01, 4.5398e-05, 1.1253e-07]])

In [6]:
a = torch.sum(encoder_out * raspredelenie.unsqueeze(2), axis=1)

In [7]:
a.size()

torch.Size([5, 10])

In [9]:
torch.cat((h, a), 1).size()

torch.Size([5, 20])